/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AddRouteImport } from './routes/add'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CollectionsIndexRouteImport } from './routes/collections/index'
import { Route as BookmarksIndexRouteImport } from './routes/bookmarks/index'
import { Route as CollectionsIdRouteImport } from './routes/collections/$id'
import { Route as BookmarksIdRouteImport } from './routes/bookmarks/$id'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AddRoute = AddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsIndexRoute = CollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksIndexRoute = BookmarksIndexRouteImport.update({
  id: '/bookmarks/',
  path: '/bookmarks/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsIdRoute = CollectionsIdRouteImport.update({
  id: '/collections/$id',
  path: '/collections/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BookmarksIdRoute = BookmarksIdRouteImport.update({
  id: '/bookmarks/$id',
  path: '/bookmarks/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/bookmarks/$id': typeof BookmarksIdRoute
  '/collections/$id': typeof CollectionsIdRoute
  '/bookmarks/': typeof BookmarksIndexRoute
  '/collections/': typeof CollectionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/bookmarks/$id': typeof BookmarksIdRoute
  '/collections/$id': typeof CollectionsIdRoute
  '/bookmarks': typeof BookmarksIndexRoute
  '/collections': typeof CollectionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add': typeof AddRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/bookmarks/$id': typeof BookmarksIdRoute
  '/collections/$id': typeof CollectionsIdRoute
  '/bookmarks/': typeof BookmarksIndexRoute
  '/collections/': typeof CollectionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add'
    | '/login'
    | '/settings'
    | '/bookmarks/$id'
    | '/collections/$id'
    | '/bookmarks/'
    | '/collections/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add'
    | '/login'
    | '/settings'
    | '/bookmarks/$id'
    | '/collections/$id'
    | '/bookmarks'
    | '/collections'
  id:
    | '__root__'
    | '/'
    | '/add'
    | '/login'
    | '/settings'
    | '/bookmarks/$id'
    | '/collections/$id'
    | '/bookmarks/'
    | '/collections/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddRoute: typeof AddRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  BookmarksIdRoute: typeof BookmarksIdRoute
  CollectionsIdRoute: typeof CollectionsIdRoute
  BookmarksIndexRoute: typeof BookmarksIndexRoute
  CollectionsIndexRoute: typeof CollectionsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add': {
      id: '/add'
      path: '/add'
      fullPath: '/add'
      preLoaderRoute: typeof AddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/': {
      id: '/collections/'
      path: '/collections'
      fullPath: '/collections/'
      preLoaderRoute: typeof CollectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks/': {
      id: '/bookmarks/'
      path: '/bookmarks'
      fullPath: '/bookmarks/'
      preLoaderRoute: typeof BookmarksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$id': {
      id: '/collections/$id'
      path: '/collections/$id'
      fullPath: '/collections/$id'
      preLoaderRoute: typeof CollectionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookmarks/$id': {
      id: '/bookmarks/$id'
      path: '/bookmarks/$id'
      fullPath: '/bookmarks/$id'
      preLoaderRoute: typeof BookmarksIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddRoute: AddRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  BookmarksIdRoute: BookmarksIdRoute,
  CollectionsIdRoute: CollectionsIdRoute,
  BookmarksIndexRoute: BookmarksIndexRoute,
  CollectionsIndexRoute: CollectionsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
